//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Users {
        
        /// <summary>
        ///   Looks up a localized string similar to: CheckUserName
        /// </summary>
        public static string CheckUserName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.CheckUserName;
            }
            return global::Resources.Users.ResourceManager.GetString("CheckUserName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: ConfirmPassword
        /// </summary>
        public static string ConfirmPassword([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.ConfirmPassword;
            }
            return global::Resources.Users.ResourceManager.GetString("ConfirmPassword", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Create
        /// </summary>
        public static string Create([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Create;
            }
            return global::Resources.Users.ResourceManager.GetString("Create", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: CreateDate
        /// </summary>
        public static string CreateDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.CreateDate;
            }
            return global::Resources.Users.ResourceManager.GetString("CreateDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Groupid
        /// </summary>
        public static string Groupid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Groupid;
            }
            return global::Resources.Users.ResourceManager.GetString("Groupid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Groups
        /// </summary>
        public static string Groups([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Groups;
            }
            return global::Resources.Users.ResourceManager.GetString("Groups", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Number
        /// </summary>
        public static string Id([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Id;
            }
            return global::Resources.Users.ResourceManager.GetString("Id", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Name;
            }
            return global::Resources.Users.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: NumberGroup
        /// </summary>
        public static string NumberGroup([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.NumberGroup;
            }
            return global::Resources.Users.ResourceManager.GetString("NumberGroup", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Password
        /// </summary>
        public static string Password([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Users.Password;
            }
            return global::Resources.Users.ResourceManager.GetString("Password", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify {0}!
        /// </summary>
        public static string RequiredFieldValidator(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.RequiredFieldValidator, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.ResourceManager.GetString("RequiredFieldValidator", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: do not match {0} and {1}!
        /// </summary>
        public static string donotmatch(object arg0, object arg1, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.donotmatch, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.ResourceManager.GetString("donotmatch", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The field {0}must be a string with a minimum length of 8 and a maximum The field {0}must be a string with a minimum length of 8 and a maximum length of 20!
        /// </summary>
        public static string minimumlength(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.minimumlength, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Users.ResourceManager.GetString("minimumlength", resourceCulture), System.Tuple.Create("0", arg0));
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UsersKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: CheckUserName
        /// </summary>
        public const string CheckUserName = "CheckUserName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ConfirmPassword
        /// </summary>
        public const string ConfirmPassword = "ConfirmPassword";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Create
        /// </summary>
        public const string Create = "Create";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: CreateDate
        /// </summary>
        public const string CreateDate = "CreateDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Groupid
        /// </summary>
        public const string Groupid = "Groupid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Groups
        /// </summary>
        public const string Groups = "Groups";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Number
        /// </summary>
        public const string Id = "Id";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: NumberGroup
        /// </summary>
        public const string NumberGroup = "NumberGroup";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Password
        /// </summary>
        public const string Password = "Password";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify {0}!
        /// </summary>
        public const string RequiredFieldValidator = "RequiredFieldValidator";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: do not match {0} and {1}!
        /// </summary>
        public const string donotmatch = "donotmatch";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The field {0}must be a string with a minimum length of 8 and a maximum The field {0}must be a string with a minimum length of 8 and a maximum length of 20!
        /// </summary>
        public const string minimumlength = "minimumlength";
    }
}
